import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "tailwindcss/tailwind.css";
import Sidebar from "@/components/sidebar";
// import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex h-full`}>
        <aside className="w-1/5 bg-gray-300 p-4">
          <Sidebar />
        </aside>
        <main className="w-4/5 pt-4 px-28 overflow-y-auto scrollbar-thin scrollbar-thumb-slate-500">
          {/* <Navbar /> */}
          {children}
        </main>
      </body>
    </html>
  );
}
