import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'tailwindcss/tailwind.css';
import Sidebar from '@/components/sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${inter.className} flex h-screen`}>
        <aside className="w-1/5 bg-gray-300 p-4">
          <Sidebar />
        </aside>
        <main className="w-4/5 p-4 bg-slate-400">
          {children}
        </main>
      </body>
    </html>
  )
}
